### ISSUE TITLE
in Builder - Remove link is emptying other editors

### ISSUE THREAD

**Issue by FDT2k** [awcodes/filament-tiptap-editor#108]
Hi, 

It happens randomly but the only way I found to reproduce this is to have a builder with several tip tap editor.
Then add a link -> save -> remove link.

The others editor will keep their content visible but for a weird reason the state of other editors are synced to "[object Object]" 

![2023-05-24_14-51](https://github.com/awcodes/filament-tiptap-editor/assets/5261645/f85dd3c0-3364-4741-9644-8bd2e94f0cb3)

The content is still is visible in the form but when saving it is set to null. 

Thank you for your help

**Comment by awcodes** [comment]
Really odd. Each instance is scoped. Can you do me a favor and provide the builder code you're using? Would help me to try to recreate.

**Comment by FDT2k** [comment]
Yes of course, thanks for your help. 

I've put together the simplest example I Have

```php 

<?php

namespace App\Filament\Resources;

use App\Filament\Blocks\ConcertDescription;
use App\Filament\Blocks\ConcertIntroduction;
use App\Filament\Resources\PostResource\Pages;
use App\Filament\Resources\PostResource\RelationManagers;
use App\Models\Post;
use Filament\Forms;
use Filament\Forms\Components\Builder as ComponentsBuilder;
use Filament\Forms\Components\Builder\Block;
use Filament\Resources\Form;
use Filament\Resources\Resource;
use Filament\Resources\Table;
use Filament\Tables;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class PostResource extends Resource
{
    protected static ?string $model = Post::class;

    protected static ?string $navigationIcon = 'heroicon-o-collection';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                ComponentsBuilder::make('content')->blocks([
                    Block::make('intro')->schema(ConcertIntroduction::getBlockSchema()),
                    Block::make('desc')->schema(ConcertDescription::getBlockSchema()),
                ])

               
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                //
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\DeleteBulkAction::make(),
            ]);
    }
    
    public static function getRelations(): array
    {
        return [
            //
        ];
    }
    
    public static function getPages(): array
    {
        return [
            'index' => Pages\ListPosts::route('/'),
            'create' => Pages\CreatePost::route('/create'),
            'edit' => Pages\EditPost::route('/{record}/edit'),
        ];
    }    
}

```

My block class "ConcertIntroduction" looks like this 


```php
<?php

namespace App\Filament\Blocks;

use FilamentTiptapEditor\TiptapEditor;
use Illuminate\View\View;

class ConcertIntroduction 
{
    protected static string $name = 'concert-introduction';

    public static function getBlockSchema(): array
    {
        return [
          
            TiptapEditor::make('content')->output('json')->profile('page')
        ];
    }

  
    public static function mutateData(array $data): array
    {
        return $data;
    }
}

```


config for profile :  
```php
//
        'page' => [ 'hr', 'bullet-list', 'ordered-list', 'checked-list', '|', 'bold', 'italic', 'lead', 'small', '|', 'link', 'media','oembed'],
//
```

The model

```php 
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $fillable=[
        'content'
    ];

    protected $casts = [
        'content'=>'json'
    ];
}

```

To reproduce: 

I put some content in two blocs and save .

I click on link then remove link. Then I save

now both content are null in database

**Comment by FDT2k** [comment]
I have a very limited understanding of what is going on but  when I remove 

```
 _this.$refs.textarea.dispatchEvent(new Event("input")); 
```

in all the plugin's callbacks, everything is fine and the problem seems to go away.  (related to json output I suppose ?)

**Comment by awcodes** [comment]
Haven't forgotten about this. Still looking into it. Thanks for you patience.

Can you try casting as 'array' instead of 'json' on the model? I wonder if there's a weird double encoding happening.

**Comment by FDT2k** [comment]
Thank you ;)

I did but nothing changed.  

After further investigation, the callbacks event I mentioned earlier are the cause of this problem. When the "input" event is trigerred Livewire receive an update with "[object Object]". I'm testing a corrected version of this package on my project and this is working.  I would have pushed a PR but I have no idea of the side effects with these events removed.

**Comment by awcodes** [comment]
Yea, honestly I'd love to drop the textarea, but it's the only way to get reactive validation. Which I'm tempted to drop anyway. Thanks for the feed back.

**Comment by awcodes** [comment]
Hey @FDT2k, I've just release v2.4.0 which should resolve this for you. If it doesn't feel free to reopen the issue.

Thanks.

**Comment by FDT2k** [comment]
Just tried it quickly but it seems to fix the issue. 

Thank you !
