### ISSUE TITLE
Problem with background colour of drop-downs in editor menu

### ISSUE THREAD

**Issue by tornikerikiashvili** [awcodes/filament-tiptap-editor#113]
<img width="1000" alt="image" src="https://github.com/awcodes/filament-tiptap-editor/assets/36791295/73ef4c8b-4fc1-44cd-b08f-d133e3912af5">

**Comment by awcodes** [comment]
Are you using a Custom theme?

I can't replicate this.

![Screen Shot 2023-05-30 at 11 13 02 AM](https://github.com/awcodes/filament-tiptap-editor/assets/3596800/7cbe9ca2-c013-480b-bbbd-7757d6fd0afd)

**Comment by tornikerikiashvili** [comment]
Yes we are using custom theme. 
Ok we will check why is the conflict with custom styles, theme is made with  filament documentation and had no problem with other package drop-downs  or elements

**Comment by awcodes** [comment]
You just need to include the plug-in's views in your themes tailwind config. There's a section at the bottom of the readme about it.

**Comment by awcodes** [comment]
Gonna close this. If you're still having issues feel free to reopen.
