### ISSUE TITLE
An invalid form control with name='' is not focusable.

### ISSUE THREAD

**Issue by elfeffe** [awcodes/filament-tiptap-editor#12]
I get that when I try to save

**Comment by elfeffe** [comment]
Latest, of both

**Comment by awcodes** [comment]
Do you have a link to any code you can share?

more screen shots of the error and your implementation?

I can’t reproduce the issue.

also what browser are you using?

**Comment by awcodes** [comment]
@elfeffe This is resolved with v0.2.13 https://github.com/awcodes/filament-tiptap-editor/releases/tag/v0.2.13

Thanks for reporting the issue. 👍
