### ISSUE TITLE
[object Object] when editing source code in json format

### ISSUE THREAD

**Issue by scvn1** [awcodes/filament-tiptap-editor#120]
I have output set to `OUTPUT_JSON` in the config file.

When I click the "Source Code" button on the editor I am just shown `[object Object]` instead of the code.

Here is the form resource code:
```
    TiptapEditor::make('body')
        ->profile('default')
        ->required()
        ->maxLength(65535)
        ->extraInputAttributes(['style' => 'min-height: 12rem;'])
        ->columnSpanFull(),
```

Plugin version: 2.5.0
Filament version: 2.17.47
Laravel version: 10.13.5

**Comment by awcodes** [comment]
Thanks, I'll have this fixed in the next release.

**Comment by awcodes** [comment]
This has been released.
