### ISSUE TITLE
When Filament is set to full width the editor has a large inner padding

### ISSUE THREAD

**Issue by scvn1** [awcodes/filament-tiptap-editor#139]
<img width="1016" alt="image" src="https://github.com/awcodes/filament-tiptap-editor/assets/60627569/06bf8a59-245d-4b97-a5cf-b653023be224">

When `'max_content_width' => 'full'` is set in the filament config file, there is a large inner padding on the TipTap field.

**Comment by awcodes** [comment]
This is by design since most rendered content won't be full width. You can disable it or even change the max width of the editor content in the config file.
