### ISSUE TITLE
[3.x] Possible regression in update/refresh event handlers

### ISSUE THREAD

**Issue by pboivin** [awcodes/filament-tiptap-editor#145]
References

- https://github.com/awcodes/filament-tiptap-editor/pull/129
- https://github.com/awcodes/filament-tiptap-editor/pull/135

Demo

https://github.com/awcodes/filament-tiptap-editor/assets/7805679/98ef6f95-759c-4f55-9367-5edf5b540ce6

**Comment by awcodes** [comment]
what does your $dispatch() look like in you're x-on:click

**Comment by pboivin** [comment]
@awcodes The method is triggered from the Livewire component with `$this->dispatch('refresh-tiptap-editors')`. I think the issue comes from Livewire 3 request batching. The event seems to be dispatched before `@entangle` has a chance to run.
