### ISSUE TITLE
[3.x] Json output return Column 'content' cannot be null on save

### ISSUE THREAD

**Issue by DanielSpravtsev** [awcodes/filament-tiptap-editor#156]
When editor output set to Json editor returns on save:
```
Column 'content' cannot be null
```

If set migration column to nullable, after save - the column is null

Migration column was set to json
Model casted to array. Also tried with json, same error.

**Environment:** 
Filament panel 3.0.39
tiptap 3.0.0 beta-1

**Component example:**
```
TiptapEditor::make('content')
     ->output(TiptapOutput::Json)
     ->required()
     ->columnSpan(2),
```

**Comment by awcodes** [comment]
Yep. Still trying to figure this one out.

**Comment by awcodes** [comment]
This will be fixed in the next release. Thanks.
