### ISSUE TITLE
[3.X] Copied images are not displayed

### ISSUE THREAD

**Issue by PluginYML** [awcodes/filament-tiptap-editor#169]
Unfortunately, when I try to paste an image from my clipboard, the image is not displayed because the img-src points to my local appdata folder.

**Comment by awcodes** [comment]
You can't copy/paste a physical file into the editor. There would be no way to display it in the rendered html. Use the insert media button.

**Comment by albertobenavides** [comment]
I have found this. But I don't get how or where should be implemented: https://github.com/ueberdosis/tiptap/issues/2912#issuecomment-1169631614
