### ISSUE TITLE
Problem install on 3.x

### ISSUE THREAD

**Issue by bubixon** [awcodes/filament-tiptap-editor#170]
![Screenshot 2023-09-13 at 10 11 28](https://github.com/awcodes/filament-tiptap-editor/assets/41482154/a65cdb8d-0b93-4887-9df1-ff94c79aa291)

**Comment by martonkaufmann** [comment]
What command did you run to install it? I just tried with the following and it worked:
`composer require awcodes/filament-tiptap-editor:^3.x-dev`

If you check the tags you can see that there is no stable release for v3 yet.

**Comment by awcodes** [comment]
v3 is in beta, but you can install it from packagist. 

`composer require awcodes/filament-tiptap-editor:"^3.0"`

Also make sure you are looking at the Readme on the 3.x branch for documentation. [https://github.com/awcodes/filament-tiptap-editor/tree/3.x](https://github.com/awcodes/filament-tiptap-editor/tree/3.x)
