### ISSUE TITLE
Tippy z-index above filament modal

### ISSUE THREAD

**Issue by MichaelMdp** [awcodes/filament-tiptap-editor#187]
### Filament Version

v3.0.73

### Plugin Version

v3.0.2

### PHP Version

8.1.16

### Problem description

when you select text and click the 'add link' button from the tippy tooltip, the tooltip is visualized above the filament modal.

![image](https://github.com/awcodes/filament-tiptap-editor/assets/1629670/cb01c29b-aea5-4536-9618-671be6403d99)

### Expected behavior

The filament modal is above the tippy tooltip.

### Steps to reproduce

- enable the default profile
- when you select text and click the 'add link' button from the tippy tooltip, the tooltip is visualized above the filament modal.

**Comment by awcodes** [comment]
I'll see if I can do anything about it, but that z-index is getting set by tippy itself and not the plugin.

**Comment by awcodes** [comment]
Looks like you didn't follow all the steps in the README about using a custom theme with the plugin. I can tell from the blue outline on the buttons. :)

https://github.com/awcodes/filament-tiptap-editor/assets/3596800/559a568d-73d5-4155-a7d1-d390ba5462b2

**Comment by MichaelMdp** [comment]
My bad, sorry, I used the wrong url in my tailwind.config.js
All working fine now, thanks for pointing this out.
