### ISSUE TITLE
Weird behavior when sorting in repeater

### ISSUE THREAD

**Issue by jyrkidn** [awcodes/filament-tiptap-editor#190]
### Filament Version

v3.0.79

### Plugin Version

v3.0.2

### PHP Version

PHP 8.2.6

### Problem description

When you add the Tiptap Editor to a sortable repeater, the prosemirror div gets duplicated. After saving it's correct again, so I don't know yet if this is an issue caused by this package or in tiptap itself.

### Expected behavior

To keep the original content

### Steps to reproduce

```php
Forms\Components\Repeater::make('items')
    ->schema([
        TiptapEditor::make('text'),
    ]),
```

### Reproduction repository

https://github.com/jyrkidn/filament-tiptap-test

### Relevant log output

```shell
See the video I made: https://github.com/jyrkidn/filament-tiptap-test/blob/master/Screen%20Recording%202023-10-18%20at%2015.33.08.mov
```

**Comment by jyrkidn** [comment]
I'll check this later as well, to see if I can find something related to this in the package.

**Comment by awcodes** [comment]
Thanks. I'll look into as soon as I get a chance. I do know though that there are some similar issues reported with Filament's own Rich/Markdown editors in repeaters. So, it could even be a Livewire issue.

**Comment by RobertsG** [comment]
Encountering the same exact issue while using in builder. But its linked to reordering.

**Comment by awcodes** [comment]
I'm thinking this is something in Livewire or Filament.

[https://github.com/filamentphp/filament/issues/7829](https://github.com/filamentphp/filament/issues/7829)

**Comment by RobertsG** [comment]
Any news on this, at the moment its quite an annoying bug that causes lost time when users enter content after a reordering the editor and the content gets thrown out on save as it was not updated in the correct duplicated text.
