### ISSUE TITLE
What do i need to do besides the official installing steps.

### ISSUE THREAD

**Issue by ajimatahari** [awcodes/filament-tiptap-editor#21]
1. i have followed every steps on your instruction on how to install this package, but it seems it was nat loading the tiptap editor js.
2. then i tried to import the tiptap core and starter-kit on the app.js file. but it seems your package failed to find the JS file too. 

both steps i take, output this error : 

- module.esm.js:416 Alpine Expression Error: tiptap is not defined
- module.esm.js:416 Alpine Expression Error: fullScreenMode is not defined

and so on with the same message "not defined", 

is there any compulsory steps outside the official steps to make this plugin works inside filament? or is it because i use alpine:3.4? Thanks in advance

**Comment by awcodes** [comment]
hey @ajimatahari,

1. Are you trying to use the plugin in the Filament Admin Panel or the standalone Forms package?
2. Alpine's current release is 3.10.2 so, I can not guarantee any functionality outside of official releases.

If you are using the standalone Forms package then there are several additional steps you'll need to make.
* Publish the vendor assets (JS/CSS)
* Include the assets on your page / layout where you are using the plugin. (The JS will need to be included before the script that initializes Alpine)
* You'll also need to have `@stack('modals')` somewhere on your page / layout too.

It is on the roadmap to support the standalone Forms package better, but for now this plugin is designed to work inside the admin panel.

**Comment by awcodes** [comment]
Sound's good. Thank you for the feedback.
