### ISSUE TITLE
Tiptap uses old curator media after media update

### ISSUE THREAD

**Issue by DanielSpravtsev** [awcodes/filament-tiptap-editor#236]
### Filament Version

3.0.97

### Plugin Version

3.0.5

### PHP Version

8.2

### Problem description

Curator version: 3.1.1

When uploading image to curator and changing default title (which is image filename by default) to my own title, pressing save and then pressing insert to tiptap, image in tiptap will be with old media title, so it need to open curator editor and press insert again to fix it 

### Expected behavior

Media in tiptap using new title provided when image uploaded and saved

### Steps to reproduce

1. Use tiptap with curator
2. In editor press upload new media
3. Upload image 
4. Press save
5. Change title to new
6. Press save
7. Press Insert media to curator
8. Verify that it uses old media title name

**Comment by awcodes** [comment]
This has been addressed with the latest Curator release. Thanks.
