### ISSUE TITLE
cannot upload image (svg)

### ISSUE THREAD

**Issue by kiranaryal** [awcodes/filament-tiptap-editor#242]
### Filament Version

2.17.55

### Plugin Version

2.6.7

### PHP Version

php 8.2

### Problem description

[https://flareapp.io/share/95JRXR05](url)

when uploading svg inside code editor
i can upload png  succesfully
 i am  new at this please any advice would be appriciated 
 
![image](https://github.com/awcodes/filament-tiptap-editor/assets/29688675/12df45fb-0670-4741-acd7-f2ca1af78c32)
![image](https://github.com/awcodes/filament-tiptap-editor/assets/29688675/8f7add97-1e2b-479f-a97d-66dc0e82cbea)

### Expected behavior

i expected no error

### Steps to reproduce

fresh laravel application 
install filament 2.17.55
install filament-tiptap 2.6.7

### Relevant log output

```shell
https://flareapp.io/share/95JRXR05
```

**Comment by kiranaryal** [comment]
![image](https://github.com/awcodes/filament-tiptap-editor/assets/29688675/8430fbe4-9de7-4187-8ae3-26c0572bb317)
I can add jpg and png  
the problem is with svg strictly

**Comment by awcodes** [comment]
This is fixed with v2.6.8

But fair warning inserting svgs will not automatically read the width and height which could affect your performance scores. You can still add them manually via the source code editor.
