### ISSUE TITLE
When using tiptap editor in filament Builder encountering an error when removing an element and saving

### ISSUE THREAD

**Issue by RobertsG** [awcodes/filament-tiptap-editor#250]
### Filament Version

v3.1.1

### Plugin Version

v3.2.7

### PHP Version

PHP 8.1

### Problem description

When editing a record that has a builder or a repeatable that contains the tiptap editor, encountering an error when trying to save or do something with the form after removing the tiptap element builder block (the document previously has to be saved with the builder element).

Do not encounter this error on v3.2.0, but appeared since updating to v3.2.7.

Example of document with the builder containing the editor:
![image](https://github.com/awcodes/filament-tiptap-editor/assets/1481648/a01b8497-e53e-4464-a0e6-e76e95e7eac6)

Example with the block removed
![image](https://github.com/awcodes/filament-tiptap-editor/assets/1481648/44e970d2-886c-4103-bc32-9f924ba18a71)

Example of the error after clicking save
![image](https://github.com/awcodes/filament-tiptap-editor/assets/1481648/a00049aa-2ecc-4449-abb9-baf0723dd1c5)

### Expected behavior

Not to encounter an error, after removing a tiptap builder block.

### Steps to reproduce

1. Create a resource that contains a builder that contains a tiptap editor.
2. Create a record with the single builder element
3. Save the record
4. Open the record again
5. Remove the builder block that contains the tiptap editor
6. Try to add a new builder block or try to save the document.
7. Should encounter an error.

**Comment by awcodes** [comment]
Can you update to Filament v3.1.18 and see if you still have the issue?

`type` is part of the Builder component and not the plugin. Could still be an issue with the plugin but need to make sure it's not an issue with core.

**Comment by digitalsimon** [comment]
I have the same issue with Filament v3.1.18 and Plugin version v3.2.7.

**Comment by RobertsG** [comment]
@awcodes will try the filament update tomorrow, although don't see how that will affect things, since I started encountering the error after updating tiptap.

**Comment by RobertsG** [comment]
Tried updating to the latest version, still encountering the issue.

**Comment by awcodes** [comment]
Thank you for checking, just wanted to make sure. Weird that the field would break the parent component though. I'll look into it.

**Comment by awcodes** [comment]
Can you make a reproduction repo for me?

It's working fine in the builder in my test app.

![Screenshot 2023-12-13 at 9 47 52 AM](https://github.com/awcodes/filament-tiptap-editor/assets/3596800/c97c8156-9b5e-4674-8667-1f4d32d6a70c)

**Comment by awcodes** [comment]
I'm not sure if it fixes your issue as there's still a bug with alpine and nested entangled state. So I'll leave this open for now, but if the later release fixes the issue please close or let me know.

Thank you for your patience..

**Comment by RobertsG** [comment]
Updated today and the issue seems to be resolved. Thanks.
