### ISSUE TITLE
Upload a picture separately and save it. The database will be empty.

### ISSUE THREAD

**Issue by lovemintblue** [awcodes/filament-tiptap-editor#275]
### Filament Version

v3.1

### Plugin Version

v3.2.14

### PHP Version

php8.1

### Problem description

Upload a picture separately and save it. The database will be empty.This should be a bug？

### Expected behavior

content is empty

### Steps to reproduce

Upload a picture separately and save it

**Comment by awcodes** [comment]
Can you give me some more information, please. I'm not understanding what you are trying to do.

**Comment by lovemintblue** [comment]
> 请给我更多信息好吗？我不明白你想做什么。

If the rich text only has one image, the saved field will be empty

**Comment by awcodes** [comment]
This will be fixed in the next release. Thank you.

**Comment by lovemintblue** [comment]
> This will be fixed in the next release. Thank you.

You're welcome, I should thank you！
