### ISSUE TITLE
Crash when disabling the "color" Extension

### ISSUE THREAD

**Issue by lpeterke** [awcodes/filament-tiptap-editor#286]
### Filament Version

v3.0.19

### Plugin Version

v2.0.0

### PHP Version

8.3.0

### Problem description

Undefined property: stdClass::$color at FilamentTiptapEditor \ Extensions\ Extensions\Color:31

### Expected behavior

No crash :D

### Steps to reproduce

I am not using the color extension, so I don't know why the error occurs. This is the config that I am using for the editor:

['heading', '|', 'bold', 'italic', 'underline', '|', 'align-left', 'align-center', 'align-right', 'align-justify', '|', 'bullet-list', 'ordered-list', '|', 'link', 'media', 'oembed' , '|', 'source']

Adding the "code" extension to the array solves the issue.

**Comment by awcodes** [comment]
Let me know if the latest release resolves this for you. Please.

**Comment by lpeterke** [comment]
Looks just fine!
