### ISSUE TITLE
using the tiptap editor in the Builder, it can be dropped into the editor.

### ISSUE THREAD

**Issue by qalainau** [awcodes/filament-tiptap-editor#29]
Using  tiptap editor in Forms\Components\Builder, if both sorting targets are tiptap editor fields, they can be dropped into the editor
![2022-07-16_0-24-23](https://user-images.githubusercontent.com/238779/179256424-b07c4fc0-1ba1-4d2f-8211-d5f40aa05d93.gif)
.

**Comment by awcodes** [comment]
Thank you for the report. 

I'll have to look into this further. I'm not 100% sure there's a way to prevent this. But i'll get back to you.

**Comment by awcodes** [comment]
This has been fixed with v0.3.8.

Thank you.
