### ISSUE TITLE
Ckeditor appeared on Tiptap editor

### ISSUE THREAD

**Issue by oldravian** [awcodes/filament-tiptap-editor#298]
### Filament Version

v3.0.19

### Plugin Version

v2.0.0

### PHP Version

PHP 8.1

### Problem description

I'm using tip tap editor on a page. While on the same page for some other purpose I'm now also using ekeditor. For some reason the ckeditor is appearing on the toolbar of tiptap editor
I added this link on my page to get ekeditor for some other purpose.

`<script src="https://cdn.ckeditor.com/4.21.0/standard-all/ckeditor.js"></script>`

How to restrict the tiptap editor to prevent that ekeditor?,

### Expected behavior

I want the CKEditor to not appear in the tip tap editor

### Steps to reproduce

Just include that ckeditor cdn on a page where the Tiptap editor is loaded
`<script src="https://cdn.ckeditor.com/4.21.0/standard-all/ckeditor.js"></script>`

**Comment by awcodes** [comment]
I'm going to need a reproduction report for this. I don't see how it's its even possible for one to affect the other.

**Comment by oldravian** [comment]
something very strange
https://easypressimagestoragebucket.storage.googleapis.com/header-images/1704241644_6594a9ecc8312.png

I just added that script into the page already loading tiptap editor
<script src="https://cdn.ckeditor.com/4.21.0/standard-all/ckeditor.js"></script>

**Comment by awcodes** [comment]
Again, I'll need a reproduction repo to be able to see what's actually happening.

**Comment by oldravian** [comment]
Hi, the problem was I had "contenteditable=true" in my tip tap so the CKEditor was automatically popping up there
I disabled this by setting up the following:
CKEDITOR.disableAutoInline = true;

The problem was related to CKEditor not with the Tiptap

**Comment by oldravian** [comment]
Hi, the problem was I had "contenteditable=true" in my tip tap so the CKEditor was automatically popping up there
I disabled this by setting up the following:
CKEDITOR.disableAutoInline = true;

The problem was related to CKEditor not with the Tiptap
