### ISSUE TITLE
not installing on windows.

### ISSUE THREAD

**Issue by debjit** [awcodes/filament-tiptap-editor#303]
### Filament Version

v3.1

### Plugin Version

v3.0

### PHP Version

PHP 8.2

### Problem description

I installed the package and got this error:
![Untitled](https://github.com/awcodes/filament-tiptap-editor/assets/565922/cbf33450-4dcf-48f7-8740-3d57158665de)
```



Warning: require(C:\projects\pathfinder\vendor\composer/../awcodes/filament-tiptap-editor/tests/helpers.php): Failed to open stream: No such file or directory in C:\projects\pathfinder\vendor\composer\autoload_real.php on line 55

Fatal error: Uncaught Error: Failed opening required 'C:\projects\pathfinder\vendor\composer/../awcodes/filament-tiptap-editor/tests/helpers.php' (include_path='.;C:/laragon/etc/php/pear') in C:\projects\pathfinder\vendor\composer\autoload_real.php:55 Stack trace: #0 
C:\projects\pathfinder\vendor\composer\autoload_real.php(38): composerRequireedefa7bacac116d0cd7af5649de92091('4d00ad875fa2196...', 'C:\\projects\\pat...') #1 C:\projects\pathfinder\vendor\autoload.php(12): ComposerAutoloaderInitedefa7bacac116d0cd7af5649de92091::getLoader() #2 C:\projects\pathfinder\public\index.php(34): require('C:\\projects\\pat...') #3 {main} thrown in C:\projects\pathfinder\vendor\composer\autoload_real.php on line 55
```

### Expected behavior

Installed correctly

### Steps to reproduce

Just install in windows in laragon system

### Relevant log output

```shell
asdfs
```

**Comment by awcodes** [comment]
You're on the wrong version of the plugin. For some reason on windows composer install ignores the ^ so it's trying to install v3.0 instead of the latest version. Add the ^ back to the value and run composer update instead.
