### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by mortezaashrafi** [awcodes/filament-tiptap-editor#309]
### Filament Version

v3.1.47

### Plugin Version

v3.0

### PHP Version

PHP 8.1

### Problem description

There is an error during installation
  require(C:\Users\XXX\XXX\Documents\GitHub\XXXX\vendor\composer/../awcodes/filament-tiptap-editor/tests/helpers.php):   
   Failed to open stream: No such file or directory  

### Expected behavior

Review and announcement to fix the problem

### Steps to reproduce

rm -rf vendor
composer install
composer dump-autoload

### Relevant log output

```shell
require(C:\Users\XXX\XXX\Documents\GitHub\XXX\vendor\composer/../awcodes/filament-tiptap-editor/tests/helpers.php):   
   Failed to open stream: No such file or directory
```

**Comment by awcodes** [comment]
For some reason on windows composer strips the ^ on install. Make sure the versions number is ^3.0 and run composer update instead.
