### ISSUE TITLE
Unable to add tools to floating toolbar

### ISSUE THREAD

**Issue by gvinson** [awcodes/filament-tiptap-editor#312]
### Filament Version

v3.1.33

### Plugin Version

v3.2.20

### PHP Version

PHP 8.2.10

### Problem description

I am unable to add some tools to the floating toolbar. For example, I have added link via the config file and tried adding it to the singular instance on the form but it does not render a link button in the floating toolbar. It is visible in the fixed toolbar at the top and there are no errors or warnings in the console.

I have another question as well. Can we hide the right side of the top toolbar? The section with the undo/redo/fullscreen buttons? I do not want them.

### Expected behavior

I expected a link modal to render that would allow me to input link details. Or inject the relevant UI/styles for typography. The only tools that worked are the ones that are there by default. I can add and remove the grid tool to the floating toolbar but not link or heading or bulleted-list.

### Steps to reproduce

Open the config file and set the `floating_menu_tools` array to `['link', 'heading']` and, if unsuccessful, will not see any buttons rendered in the floating menu.

**Comment by awcodes** [comment]
Yea. There's an issue with them at the moment. 

Personally I wouldn't use an inline element like a link in the floating menu though as it only shows on new lines with no content. 

But I'm working on it.
