### ISSUE TITLE
Overflowng images and videos

### ISSUE THREAD

**Issue by thethunderturner** [awcodes/filament-tiptap-editor#333]
### Filament Version

v3.2.37

### Plugin Version

v3.2.24

### PHP Version

8.2.15

### Problem description

You can submit videos and pictures just fine on the create page. When you visit said record on a custom view page (not extending ViewRecord), then  the pictures and videos overflow and are much bigger than they are supposed to. Example:
![image](https://github.com/awcodes/filament-tiptap-editor/assets/64212185/f5938cd1-11ea-4802-be6f-3f83fa79860a)

### Expected behavior

Expected behaviour is for the image and video to stay in the container they are supposed to be in.

### Steps to reproduce

Create a Test Record with an image or video. Then visit it in the view page

### Reproduction repository

https://github.com/thethunderturner/TipTapBugs

### Relevant log output

```shell
There are some warning on the browser, but I dont think they are related, since it works fine on the EditPage

Third-party cookie will be blocked. Learn more in the Issues tab.
tiptap.js?v=3.2.37.0:30 [tiptap warn]: Duplicate extension names found: ['bubbleMenu']. This can lead to issues
```

**Comment by awcodes** [comment]
2 things.

First: You're missing the 'vendor' in your tailwind.config.js
![Screenshot 2024-02-24 at 4 00 29 PM](https://github.com/awcodes/filament-tiptap-editor/assets/3596800/46c307b6-2f3e-4984-aeb9-05d250052d55)

Second: You need to fill the form in ViewTest.php
```php
public function mount(int | string $record): void
{
    $this->record = $this->resolveRecord($record);
    $this->data = $this->setData();

    $this->form->fill($this->data); <-this is missing
}
```

**Comment by thethunderturner** [comment]
I had the vendor in my config on my actual project. The issue was the missing form fill. Thanks

> 2 things.
> 
> First: You're missing the 'vendor' in your tailwind.config.js ![Screenshot 2024-02-24 at 4 00 29 PM](https://private-user-images.githubusercontent.com/3596800/307552599-46c307b6-2f3e-4984-aeb9-05d250052d55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MjIyMTMsIm5iZiI6MTcwODgyMTkxMywicGF0aCI6Ii8zNTk2ODAwLzMwNzU1MjU5OS00NmMzMDdiNi0yZjNlLTQ5ODQtYWViOS0wNWQyNTAwNTJkNTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjVUMDA0NTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2NiMmFmMGE1YWQ2YmY3ZGEyMGU0Y2NlNWViOGFjOGZiY2RhZWI0MzNlM2JhY2U1OTdmNDI0MGE2MDI1NzIxNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6j-dc3PX_Aw86SXXuiI7ZTT3jY7PCGl6Wrq3tJWIs9Y)
> 
> Second: You need to fill the form in ViewTest.php
> 
> ```
> public function mount(int | string $record): void
> {
>     $this->record = $this->resolveRecord($record);
>     $this->data = $this->setData();
> 
>     $this->form->fill($this->data); <-this is missing
> }
> ```
