### ISSUE TITLE
added slash "/" beginning of the url. and dont showed uploade image

### ISSUE THREAD

**Issue by msohrabifar** [awcodes/filament-tiptap-editor#339]
### Filament Version

^3.1

### Plugin Version

^3.2.25

### PHP Version

8.2

### Problem description

in the aws disk.
after upload file in editor. added slash "/" beginning of the url. and dont showed uploade image
(public disk correct worked.)

example:
/https://emarat989.storage.space/post/post-34-2024-03-/f3b2b4d1-f27c-41fd-8e1b-e8ee4c37003d.jpg

### Expected behavior

The address works correctly and the photo preview is shown correctly

### Steps to reproduce

I have no idea

**Comment by awcodes** [comment]
Are you doing anything custom with the directory's like a path generator? That url looks off too with the day missing from your directory.

**Comment by msohrabifar** [comment]
Yes, I used it. The same code in the version
"awcodes/filament-tiptap-editor": "3.1",
It works right.

**Comment by margarinas** [comment]
You should change ` 'use_relative_paths' => false ` in filament-tiptrap-editor.php
