### ISSUE TITLE
TipTap removes <span> elements

### ISSUE THREAD

**Issue by martinsjek** [awcodes/filament-tiptap-editor#345]
### Filament Version

3.2.57

### Plugin Version

3.2.25

### PHP Version

8.3

### Problem description

Tip does not allow `<span>` tags as it removes them when i add it in "Source code".

It also removes  `<div>` and `<iframe>` tags.

### Expected behavior

Allow <span> tags

### Steps to reproduce

All <span> tags in "Source code" editor

**Comment by awcodes** [comment]
This is part of the underlying Tiptap package and how Prosemirror works under the hood.

You would have to make custom Tiptap extensions to handle them.

**Comment by neelb-ast** [comment]
How do you use it in the div and span tags? Can you provide references for creating a custom tooltip to handle this?
