### ISSUE TITLE
Problem after install the package

### ISSUE THREAD

**Issue by DevYSM** [awcodes/filament-tiptap-editor#347]
### Filament Version

v3

### Plugin Version

3

### PHP Version

8.1

### Problem description

Hello Dears, 
I have installed the plugin and followed the installation guide and everything is good but after I used the editor I got the following issue.

Uncaught TypeError: editor(...).chain(...).focus(...).toggleCodeBlock is not a function
    at [Alpine] editor().chain().focus().toggleCodeBlock().run() (eval at safeAsyncFunction (http://new-bayern-web-app.test/livewire/livewire.js?id=d02a3788:1251:21), <anonymous>:3:57)
    at livewire.js?id=d02a3788:1273:23
    at tryCatch (livewire.js?id=d02a3788:1193:14)
    at livewire.js?id=d02a3788:3787:7
    at handler4 (livewire.js?id=d02a3788:3114:27)
    at livewire.js?id=d02a3788:3179:7
    at HTMLButtonElement.<anonymous> (livewire.js?id=d02a3788:3116:54)
    
    
![image](https://github.com/awcodes/filament-tiptap-editor/assets/59166666/eb9dc896-fe7e-4d40-968a-2cc7c2a8f7a1)

### Expected behavior

The expected is working normally after installation.

### Steps to reproduce

![image](https://github.com/awcodes/filament-tiptap-editor/assets/59166666/828f7fc6-d9c4-4d3f-a3f3-8d6d6c8e428c)

**Comment by DevYSM** [comment]
@awcodes 
Can you help me?

**Comment by awcodes** [comment]
well, you missed some steps about the styling and custom theme.

But your overriding the tools with an empty array so they aren't getting registered with the tiptap js editor. `->tools()` should never be an empty array. :)

**Comment by DevYSM** [comment]
@awcodes 
I have followed the documentation installations steps and I'll share a SS with you.

![image](https://github.com/awcodes/filament-tiptap-editor/assets/59166666/a27c7868-2cd0-4d97-876b-990c61ec8798)

![image](https://github.com/awcodes/filament-tiptap-editor/assets/59166666/d119d332-0e9c-4814-8f73-4318d586a4ba)

![image](https://github.com/awcodes/filament-tiptap-editor/assets/59166666/8abf3476-dc68-445a-90b2-8ef20484d0d4)

![image](https://github.com/awcodes/filament-tiptap-editor/assets/59166666/ee25b57f-0a8f-4a8a-a76d-8e7b9f0c27c5)


Finally, I have run the build command of npm.

**Comment by DevYSM** [comment]
> well, you missed some steps about the styling and custom theme.
> 
> But your overriding the tools with an empty array so they aren't getting registered with the tiptap js editor. `->tools()` should never be an empty array. :)

Thanks, It's working now.

**Comment by awcodes** [comment]
Your styles are still not getting loaded correctly. That's why you're seeing the blue ring around the buttons.

Probably has to do with your tailwind.config.js not using the filament preset.

**Comment by awcodes** [comment]
glad you got it working though. cheers.

**Comment by DevYSM** [comment]
> glad you got it working though. cheers.

All appreciate for you. <3
