### ISSUE TITLE
Cannot read properties of undefined (reading 'commands')

### ISSUE THREAD

**Issue by slovenianGooner** [awcodes/filament-tiptap-editor#366]
### Filament Version

v3.2.66

### Plugin Version

v3.3.2

### PHP Version

PHP 8.2.0

### Problem description

When trying to insert a block in the editor I get the following error in the console:

<img width="653" alt="Screenshot 2024-04-16 at 09 30 19" src="https://github.com/awcodes/filament-tiptap-editor/assets/1257629/248a2d49-74c4-417b-a790-5a5a9204e9fa">

Everything works fine in v3.3.1.

### Expected behavior

The block should insert with any problems.

### Steps to reproduce

1. Register a custom block to editor plugin.
2. Try to insert the block into the editor.
3. When clicking submit you get the above mentioned error.

**Comment by awcodes** [comment]
I can't replicate this.

try `php artisan filament:assets` to make sure you are serving the correct js files
