### ISSUE TITLE
Uncaught ReferenceError: destroyEditor is not defined

### ISSUE THREAD

**Issue by rahmap** [awcodes/filament-tiptap-editor#367]
### Filament Version

3.2.0

### Plugin Version

3.2.26

### PHP Version

8.2

### Problem description

Error when completed uplaod media image
![image](https://github.com/awcodes/filament-tiptap-editor/assets/35928710/bd7ed173-6cdf-47c1-88ed-ba259fccd8c5)

when i click Submit button, error shown in console  `Uncaught ReferenceError: destroyEditor is not defined`
![image](https://github.com/awcodes/filament-tiptap-editor/assets/35928710/0750d749-e137-43e6-a525-13231af28fdb)

and image not shown in input form
![image](https://github.com/awcodes/filament-tiptap-editor/assets/35928710/32716137-2714-4625-b8b5-311b2586120c)

### Expected behavior

Image success to upload and displayed in input form

### Steps to reproduce

Upload Image on Input Form

**Comment by rahmap** [comment]
Also image not saved in database, 

Local : Running Well
Production Server : Error

**Comment by awcodes** [comment]
I can't seem to replicate this on the latest version.

Try upgrading you also might need to run `php artisan filament:assets` to make sure you have the correct js files loading.

**Comment by rahmap** [comment]
> I can't seem to replicate this on the latest version.
> 
> Try upgrading you also might need to run `php artisan filament:assets` to make sure you have the correct js files loading.

Thanks for your help, I will try it later.

**Comment by rahmap** [comment]
Done with `php artisan filament:assets`

Thanks
