### ISSUE TITLE
Not working in Modals Anymore

### ISSUE THREAD

**Issue by AlexisSerneels** [awcodes/filament-tiptap-editor#369]
### Filament Version

v.3.2.70

### Plugin Version

v.3.3.2

### PHP Version

PHP 8.2

### Problem description

Since this release : https://github.com/awcodes/filament-tiptap-editor/releases/tag/v3.3.0, `this.editor() is underfined`is returned when trying to insert a link, or add a media, etc.
This happens for me when using the editor with an Modal from a RelationManager.

Reverting to v3.2.27 fixes the issue.

![CleanShot 2024-04-19 at 09 42 13@2x](https://github.com/awcodes/filament-tiptap-editor/assets/287688/81f88571-7ca5-4c3b-bc6d-ce9bc15bdefe)

### Expected behavior

We expect to be able to insert an image

### Steps to reproduce

- Add the field within a relation manager
- Try inserting an image

**Comment by awcodes** [comment]
Try running `php artisan filament:assets` you might not be serving the updated js file.

**Comment by AlexisSerneels** [comment]
Hi. 

That is the first thing I did. (seeing your other comment)

I’ll send you a reproduction repo in a few days if needed.

**Comment by awcodes** [comment]
Yes, please send a reproduction repo. That would help.
