### ISSUE TITLE
Rich text editor displays the content of the previous item

### ISSUE THREAD

**Issue by lovemintblue** [awcodes/filament-tiptap-editor#372]
### Filament Version

v3.2

### Plugin Version

v3.3.2

### PHP Version

php8.3

### Problem description

When I edit a piece of data, close it and open the next piece of data, the rich text displays the content of the previous piece.

### Expected behavior

When I edit a piece of data, close it and open the next piece of data, the rich text displays the content of the previous piece.

### Steps to reproduce

laravel11 + filament

**Comment by awcodes** [comment]
I'm going to need a reproduction repo to investigate this further.

**Comment by lovemintblue** [comment]
> I'm going to need a reproduction repo to investigate this further.

I created a new project and it's ok, so weird

**Comment by lovemintblue** [comment]
> 我将需要一个复制存储库来进一步调查这一点。

This problem occurs in the spa mode of filament

**Comment by awcodes** [comment]
Unfortunately SPA mode still has issues at the livewire level. So it's not something I can support at the moment. Sorry.

**Comment by lovemintblue** [comment]
> 不幸的是，SPA 模式在 Livewire 级别仍然存在问题。所以这不是我现在可以支持的。对不起。



> 不幸的是，SPA模式在Livewire级别仍然存在问题。所以这不是我现在可以支持的。但是。

It's okay thank you
