### ISSUE TITLE
Editor not reloading if integrated with filament-drafts

### ISSUE THREAD

**Issue by marvinosswald** [awcodes/filament-tiptap-editor#377]
### Filament Version

3.2.71

### Plugin Version

3.3.2

### PHP Version

8.3

### Problem description

Editor isn't reloading content if integrated with [filament-drafts](https://github.com/GuavaCZ/filament-drafts), filament-draft is using a redirect under the hood to facilitate the switch but obv doesn't do a full reload.

### Expected behavior

Editor should load new content after redirect.

### Steps to reproduce

with filament-draft installed and utilized for a given resources.

have two drafts with different content and switch between them.

**Comment by awcodes** [comment]
Sorry, I've never worked with that package, nor do I think that I'll be able to do anything about it since I don't control their package.
