### ISSUE TITLE
Adding a code block adds extra `</pre>` and `</code>` tags

### ISSUE THREAD

**Issue by AngadSethi** [awcodes/filament-tiptap-editor#384]
### Filament Version

v3.2.75

### Plugin Version

v3.3.3

### PHP Version

PHP 8.1

### Problem description

When I add a code block to the editor with some random code or text, and save it, the resultant HTML has two extra `</pre>` and `</code>` tags.

For example, writing this:

![Screenshot 2024-05-09 155953](https://github.com/awcodes/filament-tiptap-editor/assets/58678541/ed973bf7-53bf-4bfe-bce0-8c052dd108d5)

Gets stores like this in my database:

```html
<pre><code class="hljs javascript"><span class="hljs-keyword">const</span> a = <span class="hljs-number">123</span>;</code></pre></code></pre>
```

### Expected behavior

That the output would contain just one set of closing tags, not two.

### Steps to reproduce

1. Try creating an `Article` and add some text to it, and save it.
2. Inspect the stored output.

### Reproduction repository

https://github.com/AngadSethi/tiptap-editor-replicate-error

**Comment by awcodes** [comment]
I've tracked this down to a bug in the DOMSerializer in the tiptap-php package. Not much that can be done at this point.

**Comment by AngadSethi** [comment]
Oh, I'll raise this issue in `tiptap-php` then, @awcodes. Thanks a lot for checking this out!
