### ISSUE TITLE
Resize Image

### ISSUE THREAD

**Issue by mohammadapr** [awcodes/filament-tiptap-editor#399]
### Filament Version

^3.2

### Plugin Version

^3.0

### PHP Version

8.1.2

### Problem description

not working resize image after uploaded
<img width="471" alt="Screenshot 2024-06-06 at 9 13 13 at night" src="https://github.com/awcodes/filament-tiptap-editor/assets/33593620/e6e88271-5128-4be8-a1ce-3417b76388dc">

### Expected behavior

I expect to be able to click on an image and drag around the image to resize it and bring the text next to it

### Steps to reproduce

TiptapEditor::make('description')->profile('simple')->columnSpan(2),

**Comment by awcodes** [comment]
What is the actual plugin version? ^3.0 doesn't give me much insight.

**Comment by mohammadapr** [comment]
> What is the actual plugin version? ^3.0 doesn't give me much insight.
My plugin version is ^3.3.7
<img width="721" alt="Screenshot 2024-06-07 at 10 52 36 in the morning" src="https://github.com/awcodes/filament-tiptap-editor/assets/33593620/03c1d56c-da86-4bcd-b305-b3e05c39055a">

**Comment by marco-silvestri** [comment]
Is now possible to resize the images?

**Comment by awcodes** [comment]
This is a bug. I'm working on it and have a solution but have to make it work with Curator before I can release it. Thank you for your patience.

**Comment by CorwinDev** [comment]
https://github.com/awcodes/filament-tiptap-editor/assets/88144943/acd9157c-9ec0-4fb2-a75a-0b3b1274bf21

Seems to be bricked after this update

**Comment by awcodes** [comment]
Make sure you republish the assets after upgrade. Php artisan filament:assets

**Comment by CorwinDev** [comment]
I've done that still the same issue

**Comment by awcodes** [comment]
Try it with v3.4.1

**Comment by CorwinDev** [comment]
Fixed 👌
