### ISSUE TITLE
Setting gridLayouts() Does Not Restrict Grid Builder Options

### ISSUE THREAD

**Issue by onairmarc** [awcodes/filament-tiptap-editor#410]
### Filament Version

v3.2.86

### Plugin Version

v3.3.5

### PHP Version

PHP 8.3.7

### Problem description

When setting the `gridLayouts()` method to be `gridLayouts([two-columns])` no change happens in the Grid Builder

### Expected behavior

Based on the [documentation](https://github.com/awcodes/filament-tiptap-editor?tab=readme-ov-file#grid-layouts), I'm expecting the Grid Builder content to be replaced with a drop-down that only allows the `two-columns` option. Instead, no change is occurring, and I can still create unlimited columns. Is there something I'm missing?

### Steps to reproduce

Create the following TipTapEditor:

```php
TiptapEditor::make('body_content')
                    ->label('Content')
                    ->profile('default')
                    ->maxContentWidth('5xl')
                    ->gridLayouts([
                        'two-columns'
                    ]);
```

**Comment by awcodes** [comment]
'grid' and 'grid-builder' are 2 separate tools.

![Screenshot 2024-06-14 at 12 55 52 PM](https://github.com/awcodes/filament-tiptap-editor/assets/3596800/be5a5e12-090f-408c-949d-5f5e8a09e0e6)
