### ISSUE TITLE
Tiptap Editor Failing In Modal

### ISSUE THREAD

**Issue by Nathan269** [awcodes/filament-tiptap-editor#414]
### Filament Version

v3.2.91

### Plugin Version

v3.4.0

### PHP Version

PHP 8.3.8

### Problem description

The tiptap editor is failing to load the tools and also doesn't allow for the text within the editor to be edited.

### Expected behavior

The editor to display the expected tools and for me to be able to make changes to the text within the editor.

### Steps to reproduce

I'm using the kanban board filament package which when you click on an item within the kanban board, a modal pops up and contains a form. This is the code for my form:

```
protected function getEditModalFormSchema(?int $recordId): array
    {
        $job = Job::find($recordId);
        $isDisabled = false;

        if (Gate::denies('update', $job)) {
            $isDisabled = true;
        }

        return array_merge(
            [
                Placeholder::make('no_permission')
                    ->hidden(! $isDisabled)
                    ->content('You do not have permission to edit this job.'),
            ],
            JobsForm::make($isDisabled)
        );
    }
```

This issue is ongoing from this previous issue [here](https://github.com/awcodes/filament-tiptap-editor/issues/380). I left a comment near the bottom of the linked issue with an image of how my editor looks. My output has changed slightly since the update and now looks like this:
    
    
<img width="854" alt="Screenshot 2024-06-17 at 12 15 59" src="https://github.com/awcodes/filament-tiptap-editor/assets/72409095/8696196c-10c2-478c-9e62-bc57342c9d5d">

Previously, my text never even displayed within the editor. If I double click on any text, the tooltips to appear like so:

<img width="854" alt="Screenshot 2024-06-17 at 12 16 51" src="https://github.com/awcodes/filament-tiptap-editor/assets/72409095/13755d5f-1a98-4342-a689-9e98822fd14d">

I CANT delete or add any text at all.

### Relevant log output

```shell
No errors are logged within the console.
```

**Comment by awcodes** [comment]
Hmm. Hard to say. I've never worked with that plugin before so have no way of knowing what could be happening. Editor is working normally and as expected in my demo app. 

Make sure you also run 'php artisan filament:assets' in case there's any caching issues with the assets.

**Comment by Nathan269** [comment]
No luck with running 'php artisan filament:assets'. No worries though, I'll just switch to RichEditor for this project for now and if I have more time in the future, I'll dive deeper into what is causing the issue. Thanks for the quick response!

**Comment by thesubhendu** [comment]
Make sure Grammarly extension in disabled. I have seen it causing issue in modal.
