### ISSUE TITLE
StatePath being wrong after saving & reloading inside a Filament Block

### ISSUE THREAD

**Issue by pixelastronauts** [awcodes/filament-tiptap-editor#446]
### Filament Version

V3.1.102

### Plugin Version

v3.4.8

### PHP Version

PHP 8.3.9

### Problem description

When adding the TipTapEditor to a Filament Block Builder, the `statePath` of a custom block becomes incorrect after saving and reloading the page. This results in the inability to edit a custom block after saving and reloading, although everything works as expected before saving.

Adding the TipTapEditor directly to a form is working as expected.

- I've forked the repo to add some `console.log` statements for debugging: https://github.com/pixelastronauts/filament-tiptap-editor
- A video demonstrating the issue can be found here: 

https://github.com/user-attachments/assets/8af69199-18c9-49b4-b797-0f3d9f29ef9b

### Expected behavior

The edit functionality should continue to work properly after saving and reloading the page.

### Steps to reproduce

1. Add TipTapEditor to a Filament Block Builder
2. Create and edit a custom block (works as expected)
3. Save the changes
4. Reload the page
5. Attempt to edit the custom block (fails due to incorrect `statePath`)

**Comment by capetrel** [comment]
Hi,
don't know if it can't help, but i have a similar issue, with somthing else, deleting a custom block, delet another one in an another builder block :
![Sans-titre---1](https://github.com/user-attachments/assets/a521ff93-3d87-4d34-a116-40fe306d12e7)

**Comment by LuisLeguizamon** [comment]
@pixelastronauts I'm facing a similar issue. Could you kindly guide me on how you rebuilt the package to display the logs added here? https://github.com/awcodes/filament-tiptap-editor/commit/8f2831087941ea8da849a79b57cb9d24ed96f286
