### ISSUE TITLE
Uploading an image with capital file extension adds a link to the image, not the image itself.

### ISSUE THREAD

**Issue by kylxbn** [awcodes/filament-tiptap-editor#451]
### Filament Version

v3.2

### Plugin Version

3.4.9

### PHP Version

PHP 8.3

### Problem description

Uploading an image where the file extension is all capital (for example, `.JPG`) results in a link to the file (`<a href="...">`), and not the image itself (`<img src="...">`).

### Expected behavior

An `img` tag will be added.

### Steps to reproduce

Try to add an image where the file extension is all capital.

**Comment by kylxbn** [comment]
Found the issue. I submitted a pull request. I hope my pull request was done correctly. Apologies if not.

**Comment by awcodes** [comment]
Fixed by #452
