### ISSUE TITLE
Selecting left align after save doesn't apply text-align: left;

### ISSUE THREAD

**Issue by l-mtc** [awcodes/filament-tiptap-editor#474]
### Filament Version

v3.2.112

### Plugin Version

v3.4.14

### PHP Version

PHP 8.3.11

### Problem description

If you click center or right, then save and try to left align it doesn't add text-align: left; instead it adds an empty style:
e.g. `<p style="text-align: center; ;">test</p>`

### Expected behavior

text-align: left; to be added, ideally existing styles replaced

### Steps to reproduce

1. Add text to block
2. Center or right align text
3. Save
4. Try left align text

**Comment by awcodes** [comment]
Please try upgrading to the latest version. I am unable to replicate the issue on 3.4.16
