### ISSUE TITLE
error in feature insert media,video, gridbuilder etc

### ISSUE THREAD

**Issue by RAFIFEFZET** [awcodes/filament-tiptap-editor#488]
### Filament Version

v.3.2.0

### Plugin Version

v.3.4

### PHP Version

v.8.1.6

### Problem description

this error occurs when im trying feature insert media,video, gridbuilder etc 
Error: Method Filament\Forms\Components\Toggle::dehydratedWhenHidden does not exist.

### Expected behavior

how to solve it?

### Steps to reproduce

-

**Comment by RAFIFEFZET** [comment]
I think this error is due to a mismatched version, what plugin version for Filament 3.2?

**Comment by awcodes** [comment]
yea, you need to update your Filament version. latest is v3.2.119
