### ISSUE TITLE
Image not shown after edit its properties.

### ISSUE THREAD

**Issue by Philip-Droubi** [awcodes/filament-tiptap-editor#500]
### Filament Version

v3.2.124

### Plugin Version

v3.4.19

### PHP Version

PHP 8.1.17

### Problem description

I noticed a problem when editing an image that has been added using mediaAction. This problem does not appear during the adding process, but only during the image updating process.
Another problem is that the FileUploader gets stuck in the process of loading the image.

I'm using the local storage for saving images in, and I'm not sure if this is only me or it's a bug?

Currently I fixed it by adding `/storage/` to `prepend` in `EditMediaAction` file on line 145 (without any edit on MediaAction).

tiptap-editor code used in the video:

```php
TiptapEditor::make('body')
             ->columnSpanFull()
             ->extraInputAttributes(['style' => 'min-height: 12rem;'])
             ->disableFloatingMenus()
             ->required(),
```

## Video:

In this video we can see the problem and how I fixed it.

https://github.com/user-attachments/assets/1e6592b5-48cd-4031-9776-b3c36b923595

### Expected behavior

Showing image after editing its properties.

### Steps to reproduce

- Insert an image and submit it.
- Try to update some of its properties (eg. height).
- Submit the changes.

### Reproduction repository

N/A

### Relevant log output

```shell
N/A
```

**Comment by awcodes** [comment]
See #425
