### ISSUE TITLE
Possible error if content key not found

### ISSUE THREAD

**Issue by dgironella** [awcodes/filament-tiptap-editor#504]
### Filament Version

3.2.124

### Plugin Version

3.4.19

### PHP Version

8,2

### Problem description

On line 196 of file TiptapEditor.php have this line
`$content = $document['content'];`

If key content not exist, this can generate an error.

### Expected behavior

Check if key exist

### Steps to reproduce

Modify database content. Dont have a repo to reproduce.

**Comment by awcodes** [comment]
what is the use case for the key not to exist. if the data was saved with the editor then it will always exist.

**Comment by dgironella** [comment]
In my case, I use the same database field to store either TipTapEditor content or plain text input. The user can change the type using a selector, but in this case, an error occurs.

I extended your class, and change this function, for me is needed to use tiptapeditor.

**Comment by awcodes** [comment]
I don't think that use case is something to support in the plugin as it's not a common use case. And the Tiptap converter is expecting the content to be in a specific format that needs that content key.
