### ISSUE TITLE
Package not compatible anymore with PHP < 8.1

### ISSUE THREAD

**Issue by arjendejong12** [awcodes/filament-tiptap-editor#51]
We discussed this yesterday in the Filament Discord. This package doesn't work anymore in environments with PHP below 8.1 since the 'output' feature update, because the enum class is always getting loaded.
https://github.com/awcodes/filament-tiptap-editor/blob/c6b14dffeb4ada0d36c23788d70716b21c7f5f76/src/TiptapEditor.php#L11
https://github.com/awcodes/filament-tiptap-editor/blob/c6b14dffeb4ada0d36c23788d70716b21c7f5f76/src/TiptapEditor.php#L51

**Comment by awcodes** [comment]
Thank you. I'll get this addressed today. And post in discord when it's fixed.

**Comment by awcodes** [comment]
This should be resolved with v1.0.6.

Let me know if you have any other issues.

Thanks.
