### ISSUE TITLE
Live debounce is not working

### ISSUE THREAD

**Issue by mathieutu** [awcodes/filament-tiptap-editor#520]
### Filament Version

v3.2.129 

### Plugin Version

v3.4.22

### PHP Version

8.4.1

### Problem description

Hey, 
`->live()` function is working, but not `->live(debouce: 500)`.

When doing that the editor doesn't load and we can see some errors in console.
<img width="954" alt="Screenshot 2024-12-12 at 11 29 57" src="https://github.com/user-attachments/assets/70869f5d-a55d-4053-945a-ebcdb8baa5e8" />

<img width="1019" alt="Screenshot 2024-12-12 at 11 29 06" src="https://github.com/user-attachments/assets/506833e8-4fc7-4ec7-b010-6433679cf423" />

Thanks,
Mathieu.

**Comment by awcodes** [comment]
May I ask what you need live for? It is really bad practice to have live on any kind of long text field. Even with debounce it's going to create more server requests than you actually need.

**Comment by mathieutu** [comment]
I need to compute some fields from the text (extract some variables from placeholders in the text).

**Comment by awcodes** [comment]
Hmm, not sure what the issue is in this case. The debounce just adds the '.1s' to the entangle. But that shouldn't be breaking the alpine component. Can you provide a reproduction repo?

**Comment by mathieutu** [comment]
Sorry, for now, I've uninstalled the package and played with the official RichEditor. But you should be able to reproduce just by passing any value to debounce in any of the projects that uses this plug-in.

I'll invest more if I need this package back later.

**Comment by awcodes** [comment]
No worries. Do what you need.

**Comment by thijskuilman** [comment]
Hey @mathieutu. If you are still interested in a solution for this: I have created a PR that should solve this. See https://github.com/awcodes/filament-tiptap-editor/pull/553

**Comment by mathieutu** [comment]
Thanks!
