### ISSUE TITLE
Setting Output Causes Cursor To Jump To End

### ISSUE THREAD

**Issue by freshleafmedia** [awcodes/filament-tiptap-editor#58]
When the output type is set to anything other than `TiptapEditor::OUTPUT_HTML` the cursor jumps to the end of the field anytime a key is pressed:

```php
TiptapEditor::make('text')
    ->output(TiptapEditor::OUTPUT_JSON)
```

**Comment by awcodes** [comment]
Resolved with latest release. (v2.0.2)

Thanks.
