### ISSUE TITLE
Issue When Saving Unchanged JSON

### ISSUE THREAD

**Issue by freshleafmedia** [awcodes/filament-tiptap-editor#60]
Given the following code:

`Resources/TestResource.php`
```php
class TestResource extends Resource
{
    protected static ?string $model = Test::class;

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                TiptapEditor::make('test')
                    ->output(TiptapEditor::OUTPUT_JSON),
            ]);
    }

    //...

}
```

`Models/Test.php`
```php
class Test extends Model
{
    protected $fillable = [
        'test',
    ];

    public $casts = [
        'test' => 'json',
    ];
}
```

When text is entered and you press save the JSON data is persisted to the database as expected. If you refresh the page and without changing the value press save `null` is persisted rather than the displayed value.

Additionally, and I suspect this is related, if you enter text and press save and then without refreshing the page press save again an error is thrown:

![20221128-2117](https://user-images.githubusercontent.com/10062339/204382923-03337c70-a5eb-428f-bb87-4e61ff94fa72.png)

Inspecting the value of `$state` on the first save gives:

![20221128-2126](https://user-images.githubusercontent.com/10062339/204384341-a8015c89-9258-45de-9c83-9291d88efbf1.png)

On the second save:

![20221128-2123](https://user-images.githubusercontent.com/10062339/204384206-80ba1fbb-3cad-43c3-9208-9c97f2b256d8.png)

**Comment by awcodes** [comment]
Was going to get to this today. Other things took priority. Sorry.

Should be able to get to it soon.

**Comment by awcodes** [comment]
I think v2.0.3 will get you sorted. Let me know.

Also, thanks for being a product tester. 🤣

**Comment by freshleafmedia** [comment]
That seems to have fixed it :tada: 

Happy to do some testing! I appreciate you taking the time to look at the issue :+1:
