### ISSUE TITLE
I can't add class for ul or li tag. 

### ISSUE THREAD

**Issue by erenergul** [awcodes/filament-tiptap-editor#63]
Hi , Its good package and I like it so far but I have an issue. I can't add any ul or li class when im in source code.

`<ul class="IT WILL DISAPPEAR AFTER SAVE"><li ><p><a class="text-blue-500" href="www.asda.com" target="_blank" as_button="false" button_theme="">Alanya Pamukkale Tour</a></p></li></ul>`

**Comment by awcodes** [comment]
Sorry it's taken this long to get back to you on this. 

I'll keep looking for a way to make this better, but tiptap and prose mirror are very strict about what attributes can be saved to a tag or mark. 

So to make this work I would basically have to extended all of the default extensions, which i'm not willing to do at the moment.

Also custom extensions will be released soon in this plugin, which you can use to extended the tags and marks that you need to be able to do this with. 

Sorry.
