### ISSUE TITLE
links not working at all for me

### ISSUE THREAD

**Issue by pintend** [awcodes/filament-tiptap-editor#64]
when clicking links tool the whole parent livewire component goes blank. i cant see to trace where/why this is happening

if `$wire.dispatchFormEvent('tiptap::setLinkContent', '{{ $statePath }}', linkProps);` is commented it out in `link.blade.php` it obviously doesn't ping the server. but the function which is regiatered to listen on [`tiptap::setLinkContent`](https://github.com/awcodes/filament-tiptap-editor/blob/2.x/src/TiptapEditor.php#L101) is never run either. 

im confused with the event lifecycle and why the page goes blank

i am using this in a form with the filament-tools package

**Comment by awcodes** [comment]
Couple questions:
* What version of Filament are you using?
* What version of the plugin are you using?

I can't seem to replicate this, nor have I used filament-tools package, so I don't know if there is a conflict there.
