### ISSUE TITLE
Link doesn't work 

### ISSUE THREAD

**Issue by lotarbo** [awcodes/filament-tiptap-editor#67]
Hello, i use filamentphp admin with this field.
My model has field `hero` - json and same cast
I attach video how it looks like. After i click `save changes` i do refresh page

edit: `bold` works as expected

### Versions
```
PHP 8.2.0 
laravel/framework                      v9.48.0 
filament/filament                      v2.16.65 
awcodes/filament-tiptap-editor         v2.0.6 
```

https://user-images.githubusercontent.com/1766890/214573222-6f3bad8a-1a73-414a-934b-2c1a2fc574c4.mov

**Comment by awcodes** [comment]
I'll have look today. Thanks.
