### ISSUE TITLE
Uncaught ReferenceError: fullScreenMode is not defined

### ISSUE THREAD

**Issue by rubenvanerk** [awcodes/filament-tiptap-editor#73]
After upgrading to `2.x`, I'm getting errors in the javascript console:

`Uncaught ReferenceError: fullScreenMode is not defined`

`Uncaught ReferenceError: isActive is not defined`

Are there any changes that I should make to upgrade to `2.x`? Is there an upgrade guide available?

**Comment by awcodes** [comment]
There a few upgrade steps listed in the readme. But those are JavaScript errors, so maybe it's a browser cache issue. Also make sure you are using the appropriate output type for your storage.
