### ISSUE TITLE
No backgound color in light mode for fullscreen editor

### ISSUE THREAD

**Issue by grahammtbr** [awcodes/filament-tiptap-editor#8]
Like the title says, there's no background colour set in the tiptap-content div for lightmode.

`<div class="tiptap-content max-h-[40rem] h-auto overflow-scroll rounded-b-md dark:bg-gray-700" x-ref="element">`

Needs a bg-white, or it the editor becomes transparent when going fullscreen ;)

**Comment by awcodes** [comment]
I e got some other styling fixes to make. I’ll include this in those fixes. Thank you.

**Comment by awcodes** [comment]
Thanks again @grahammtbr 

This is fixed in the latest version: https://github.com/awcodes/filament-tiptap-editor/releases/tag/v0.2.10

**Comment by grahammtbr** [comment]
:+1:
