### ISSUE TITLE
bug: align left didn't work in rtl version

### ISSUE THREAD

**Issue by AmirAghaee** [awcodes/filament-tiptap-editor#81]
In the RTL version, aligning text left doesn't work, but it works fine in the LTR.

**Comment by awcodes** [comment]
Hey @AmirAghaee,
I'm still looking into this. It looks like it might be a bug in Tiptap's textAlign extension, but not 100% sure yet.

**Comment by awcodes** [comment]
Support has been added in v2.2.2.

You will need to add the `direction` key to you config and set it to 'rtl' if you've already published it.
