### ISSUE TITLE
Strange behavior with bold tool

### ISSUE THREAD

**Issue by lotarbo** [awcodes/filament-tiptap-editor#91]
I can't select text and make it bold, each time i click bold cursor moved to start position
plugin version v2.2.5
I attach video

https://user-images.githubusercontent.com/1766890/223794152-d163c02a-a86a-4342-b8ac-2e16a40a39fa.mov

**Comment by awcodes** [comment]
Thanks for letting me know.

This is a bug introduced by 2.2.4.

I will get to it as soon as I can. If it's affecting anything in production you can lock the version to 2.2.3 until I can get it fixed.
